import {StyleSheet}from 'react-native'
import fonts from '../../res/fonts';
const styles= StyleSheet.create({
    container:{
     //padding:20,
     //justifyContent:'center',
     //alignItems:'center',
     //alignContent:'center',
     flex:1,
     backgroundColor:'white',
    },
    // insideContainer:{
    //   elevation:5,
    //   borderRadius:10,
    //   backgroundColor:'white',
    //   width:350,
    //   padding:20,
    // },
    totalDayContainer:{
      //alignItems:'center',
      //justifyContent:'center',
      //elevation:4,
      backgroundColor:'#F6FAFF',
      //borderRadius:5,
      //marginBottom:10,
      //borderWidth:.5,
      height:90,
      padding:20,
    },
    top:{
        flexDirection:'row',
        //justifyContent:'center',
        //alignItems:'center',
        //marginRight:40,
    },
    availableLeave:{
        //marginRight:20,
        fontSize:18,
        fontFamily:fonts.text,
        marginBottom:8,
    },
    totalDayTextSick:{
        marginRight:20,
        marginLeft:80,
        fontSize:18,
        fontFamily:fonts.loginplaceholder,
      },
    totalDayText:{
      //marginRight:20,
      fontSize:18,
      fontFamily:fonts.loginplaceholder,
    },
    pickerView:{
      //flexDirection:'row',
      marginBottom:10,
      paddingLeft:20,
    },
   
    pickerText:{
      marginRight:20,
      fontSize:18,
      marginTop:10,
      fontFamily:fonts.name,

    },
    pickers:{
      height: 50, 
      width: 200,
      borderWidth:1,
      borderColor:'red',
    },
    durationText:{
      fontSize:18,
      marginBottom:10,
      fontFamily:fonts.name,
      paddingLeft:20,
    },
    dateView:{
        flexDirection:'row',
        marginBottom:10,
        //paddingLeft:20,
        //borderWidth:.5,
        //borderColor:'grey',
        marginLeft:20,
        marginRight:20,
        borderRadius:10,
        backgroundColor:'#F2F3F5',
        justifyContent:'center',
        alignItems:'center'
      },
    durationFromInput:{
      //borderEndWidth:2,
     // borderColor:'grey',
      height:40,
      width:250,
     
      //borderWidth:2,
    },
    CalendarIcon:{
      marginLeft:50,
      //marginTop:10,
    },
    modalDurationForm:{
      justifyContent:'center',
      alignItems:'center',
      elevation:4,
      height:150,
      marginTop:250,
      marginLeft:20,
      marginRight:20,
      backgroundColor:'white',
      flex: .8,
      borderRadius:10,
      shadowColor: "#000",
      shadowOffset: {
          width: 0,
          height: 2
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      padding:10,
    },
    calendarDetails:{
      borderWidth: 1,
      borderColor: 'gray',
      //height: 200,
    },
    halfDayView:{
      //flex:1,
      flexDirection:'row',
      marginBottom:10,
      // marginLeft:20,
       borderColor:'#278BFF',
       //borderWidth:1,
      // marginRight:20,
      // borderRadius:10,
      //height:50,
      marginTop:10,
      //justifyContent:'center',
      //alignItems:'center',
    },
    fullDayTouch:{
      flex:.6,
       borderColor:'#278BFF',
       borderWidth:1,
       borderRadius:10,
     // backgroundColor:'#278BFF',
      //borderRadius:10,
      marginLeft:20,
      justifyContent:'center',
      alignItems:'center',
      height:45,
    },
    fullDayText:{
      fontSize:18,
     // marginLeft:10,
      //marginRight:20,
      fontFamily:fonts.logintitle,
    },
    halfDayTouch:{
      flex:.6,
      borderColor:'#278BFF',
      borderWidth:1,
      borderRadius:10,
      backgroundColor:'#278BFF',
      //borderRadius:10,
      marginRight:20,
      height:45,
      justifyContent:'center',
      alignItems:'center',
    },
    halfDayText:{
      fontSize:18,
      //marginLeft:10,
     // marginRight:20,
     fontFamily:fonts.logintitle,
    },
    mornignIcon:{
      
    },
    eveningIcon:{
      marginLeft:20,
    },
    morningView:{
      marginTop:20,
      flexDirection:'row',
      marginBottom:10,
      paddingLeft:20,
      //borderWidth:1,
    },
    morningText:{
      fontSize:18,
      fontFamily:fonts.logintitle,
      //marginRight:20,
    },
    eveningText:{
      //marginLeft:20,
      fontSize:18,
      fontFamily:fonts.logintitle,
    },
    reasonView:{
      marginBottom:20,
      paddingLeft:20,
      paddingRight:20,
    },
    reasonText:{
      fontSize:18,
      fontFamily:fonts.name,
      marginBottom:10,
    },
    reasonTextInput:{
      //borderWidth:1,
      borderRadius:10,
     // flex:6,
     height:98,
      backgroundColor:'#F2F3F5',
    },
    submitContainer:{
     backgroundColor:'#278BFF',
     marginLeft:20,
     marginRight:20,
     //flex:6,
     borderRadius:10,
     height:50,
     alignItems:'center',
     justifyContent:'center',
    },
    submitText:{
      fontSize:18,   
      fontFamily:fonts.signin, 
    },
    keyboard:{
      //paddingBottom:10,
      //height:20,
    },
  });
  export default styles;